# Generated by Django 5.1.1 on 2024-10-28 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_noticedata"),
    ]

    operations = [
        migrations.CreateModel(
            name="eventdata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("event_title", models.CharField(max_length=100)),
                ("event_img", models.ImageField(upload_to="profile_img")),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("description", models.CharField(max_length=200)),
            ],
        ),
    ]
