# Generated by Django 4.1 on 2024-11-23 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("code", models.CharField(max_length=200)),
                ("linenos", models.BooleanField(default=False)),
                ("language", models.CharField(max_length=100)),
                ("style", models.CharField(max_length=100)),
            ],
        ),
    ]
